apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    name: hello-world-service
    app: python-hello-world
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    name: python-hello-world-pod
    app: python-hello-world