apiVersion: v1
kind: Service
metadata:
  name: test-environment-service
  labels:
    name: test-environment-service
    app: test-environment
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5001
  selector:
    name: test-environment-pod
    app: test-environment